### ISSUE TITLE
Unable to crop photo with YII_DEBUG=false

### ISSUE THREAD

**Issue by vsulak** [dpodium/yii2-widget-upload-crop#1]
**assets/js/uploadcrop.min.js** used when YII_DEBUG=false is unable to crop image with infinite loader present. When replaced by standard version of uploadcrop.js, cropping works fine.

**Comment by sionghuat** [comment]
Hi vsulak, 

Thanks for the report, it should be fixed under version 0.4. Can you do an update and see whether the problem persist.
